- Haptic Feedback added
monoqlo/ExpandingMenu pull request #34
Opened 2018-10-08 09:17 UTC by kamrankhan07

- Some code refactoring
- Menu Button rotate image is added
- Default values are changed

2018-10-10 00:50 UTC, monoqlo commented
@kamrankhan-chilindo 

Thanks for your pull request!
I'll check it soon. Please wait a few days.

I don't have enough time to develop this library, so I'm so grateful for your help.

2018-10-14 04:11 UTC, monoqlo requested changes
@kamrankhan07 @kamrankhan-chilindo   I appreciated your changes😂

But I found a few points to be discussed.
Please change it or describe your purpose.

2018-10-14 04:11 UTC, monoqlo commented on ExpandingMenu/Classes/ExpandingMenuButton.swift
> +    open var expandingAnimations: CustomAnimationOptions = [.move, .menuButtonRotate]
Please use `[.default]` or please describe the reason why this value should be `[.move, .menuButtonRotate]`.

2018-10-14 04:11 UTC, monoqlo commented on ExpandingMenu/Classes/ExpandingMenuButton.swift
> +    @objc open var playSound: Bool = false {
Please use `true` or please describe the reason why this value should be `false`.

2018-10-14 04:11 UTC, monoqlo commented on Example/ExpandingMenu/ViewController.swift
> +        menuButton.playSound = false
I'd like to show the default behavior to would-be users, so remove these lines.

2018-10-14 23:51 UTC, kamrankhan07 commented on ExpandingMenu/Classes/ExpandingMenuButton.swift
> +    open var foldingAnimations: CustomAnimationOptions = [.move, .menuButtonRotate]
I will add default, I changed it because 'default' was using all animations and it was not desirable for me.

2018-10-14 23:56 UTC, kamrankhan07 reviewed
I have made all the changes, please check again.

2018-10-20 05:11 UTC, monoqlo commented
Thanks for your changes! I'll merge it.

2018-10-20 05:12 UTC, monoqlo approved these changes

2018-10-20 05:12 UTC, merged

2018-10-22 03:29 UTC, kamrankhan07 commented
Thanks